#!/bin/sh
TMP=/tmp
if dvipdfm -e -z0 $@
then
   gs -r12 -dNOPAUSE -dBATCH -sDEVICE=png16 -sOutputFile=$TMP/$1.%d $1.pdf;
   dvipdfm -t $@;
fi   
# gs -r12 -dNOPAUSE -dBATCH -sDEVICE=jpeg  -sOutputFile=$TMP/$1.%d $1.pdf

