.TH dvipdfm 1 5/28/2001
.SH NAME
dvipdfm \- Produce PDF files directly from DVI files

.SH SYNOPSIS
.B dvipdfm
[
.I options 
]
.IR file [.dvi]

.SH DESCRIPTION
The program
.B dvipdfm
produces a PDF file directly from a DVI file.


.SH OPTIONS

.SH ENVIRONMENT

.SH FILES

.SH "SEE ALSO"
.BR tex "(1), " dvips "(1)"

.SH AUTHOR
Mark A. Wicks

